name: Run Puppeteer Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --shm-size=2g

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer script
      run: node your-script.js
      env:
        DISPLAY: :99